### ISSUE TITLE
'base_path' argument error

### ISSUE THREAD

**Issue by lamhai1401** [gangverk/flask-swagger#63]
I'm using `flask-swagger-0.2.14`
but when i ran the first example like in your `README.md`

 ```python 
@app.route("/spec")
def spec():
    base_path = os.path.join(app.root_path, 'docs')
    return jsonify(swagger(app), from_file_keyword="swagger_from_file", base_path=base_path)

@app.route('/test', methods=['POST'])
def login():
    """
    swagger_from_file: test.yml
    """
```

I got this error
```
swagger() got an unexpected keyword argument 'base_path'
```

Could you tell me how to resolve it!
Thank in advance!

**Comment by OhMaley** [comment]
I have the same issue.
No release since 2019/03/26 (date of release of the version you are using: 0.2.14). The `base_path` argument has been introduced in #48 from 2020/05/12, so you won't be able to use it until the next release.

One thing you can do is to use the master branch (which includes the changes you need). To use the master branch:
`pip install git+https://github.com/getsling/flask-swagger@master`

**Comment by aninhalacerda** [comment]
Same issue here.
Are you planning on releasing soon?

**Comment by Mattwmaster58** [comment]
I think the solution mentioned above is the best we have for now. One thing I had to do was first uninstall flask-swagger, I suspect this is because master and PyPi specify they are the same version, whereas master actually has updated code. (Probably could've used `--forced-reinstall`, but be aware this reinstalls dependencies, and the dependency resolution will be done against what _this_  package specifies, not what's in your requirements.txt or whatever, so TLDR, just uninstall and reinstall for the least problems ;))

I would caution against using the master branch, and instead pick a commit like the latest one as of the time of this comment, `23408f4`

So your full pip install command:
```
pip uninstall -y flask-swagger && pip install git+https://github.com/getsling/flask-swagger@23408f4
```
